<!DOCTYPE html>
<html>
<head>
    <title>Insertion</title>
</head>
<body>
<div class="header">
    <h1>OldPeopleRelative</h1>

</div>

<form action="OLD_REL.PHP" method="POST">
    <table>
        <tr>
            <td>ID</td>
            <td><input type="text" name="OR_ID" class="textInput"></td>
        </tr>

        <tr>
            <td>NationalID</td>
            <td><input type="text" name="OR_NID" class="textInput"></td>
        </tr>

        <tr>
            <td>Name</td>
            <td><input type="text" name="Name" class="textInput"></td>
        </tr>

        <tr>
            <td>Address</td>
            <td><input type="text" name="Address" class="textInput"></td>
        </tr>

        <tr>
            <td>Email</td>
            <td><input type="text" name="Email" class="textInput"></td>
        </tr>


        <tr>
            <td>Blood_group</td>
            <td><input type="text" name="blood_group" class="textInput"></td>
        </tr>


        <tr>
            <td>Relation</td>
            <td><input type="text" name="Relation" class="textInput"></td>
        </tr>

        <tr>
            <td>Ammount</td>
            <td><input type="number" name="Ammount" class="textInput"></td>
        </tr>


        <tr>

            <td><input type="submit" name="ok" value="Insert"></td>
        </tr>

    </table>

</form>

</body>
</html>




      
