<!DOCTYPE html>
<html>
<head>
    <title>Insertion</title>
</head>
<body>
<div class="header">
    <h1>TREATS</h1>

</div>

<form action="TREATS.php" method="POST">
    <table>
        <tr>
            <td>O_ID</td>
            <td><input type="text" name="OID" class="textInput"></td>
        </tr>

        <tr>
            <td>DOC_ID</td>
            <td><input type="text" name="DOCID" class="textInput"></td>
        </tr>

        <tr>
            <td>TREATMENT DATE</td>
            <td><input type="date" name="BD"></td>
        </tr>

        <tr>
            <td>TREATMENT FEE</td>
            <td><input type="number" name="FEE" class="textInput"></td>
        </tr>


        <tr>

            <td><input type="submit" name="ok" value="Insert"></td>
        </tr>

    </table>

</form>

</body>
</html>




      
