<!DOCTYPE html>
<html>
<head>
    <title>Insertion</title>
</head>
<body>
<div class="header">
    <h1>RELATES</h1>

</div>

<form action="relates_in.php" method="POST">
    <table>
        <tr>
            <td>Relative ID</td>
            <td><input type="text" name="RID" class="textInput"></td>
        </tr>

        <tr>
            <td>OldPEOPLE ID</td>
            <td><input type="text" name="OID" class="textInput"></td>
        </tr>

        <tr>
            <td>Relation</td>
            <td><input type="text" name="Relation" class="textInput"></td>
        </tr>

        <tr>

            <td><input type="submit" name="ok" value="Insert"></td>
        </tr>

    </table>

</form>

</body>
</html>




      
