<!DOCTYPE html>
<html>
<head>
    <title>Insertion</title>
</head>
<body>
<div class="header">
    <h1>Relative Phone</h1>

</div>

<form action="OR_PHONE.php" method="POST">
    <table>
        <tr>
            <td>Old Relative ID</td>
            <td><input type="text" name="ORID" class="textInput"></td>
        </tr>

        <tr>
            <td>PHONE NO.</td>
            <td><input type="text" name="Phone" class="textInput"></td>
        </tr>

        

        <tr>

            <td><input type="submit" name="ok" value="Insert"></td>
        </tr>

    </table>

</form>

</body>
</html>




      
